import '../models/course.dart';

class SampleData {
  static List<Course> getSampleCourses() {
    final now = DateTime.now();
    
    return [
      Course(
        id: '1',
        name: '高等数学',
        teacher: '张教授',
        location: '教三楼 201',
        dayOfWeek: 1,
        startSection: 1,
        endSection: 2,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFF3B82F6,
        createdAt: now,
        updatedAt: now,
      ),
      Course(
        id: '2',
        name: '大学英语',
        teacher: '李老师',
        location: '外语楼 305',
        dayOfWeek: 1,
        startSection: 3,
        endSection: 4,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFF10B981,
        createdAt: now,
        updatedAt: now,
      ),
      Course(
        id: '3',
        name: '计算机基础',
        teacher: '王教授',
        location: '信息楼 102',
        dayOfWeek: 2,
        startSection: 1,
        endSection: 2,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFFF59E0B,
        createdAt: now,
        updatedAt: now,
      ),
      Course(
        id: '4',
        name: '线性代数',
        teacher: '赵教授',
        location: '教三楼 205',
        dayOfWeek: 2,
        startSection: 3,
        endSection: 4,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFFEF4444,
        createdAt: now,
        updatedAt: now,
      ),
      Course(
        id: '5',
        name: '数据结构',
        teacher: '陈教授',
        location: '信息楼 301',
        dayOfWeek: 3,
        startSection: 5,
        endSection: 6,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFF8B5CF6,
        createdAt: now,
        updatedAt: now,
      ),
      Course(
        id: '6',
        name: '大学物理',
        teacher: '刘教授',
        location: '理科楼 401',
        dayOfWeek: 3,
        startSection: 7,
        endSection: 8,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFFEC4899,
        createdAt: now,
        updatedAt: now,
      ),
      Course(
        id: '7',
        name: '体育',
        teacher: '孙教练',
        location: '体育馆',
        dayOfWeek: 4,
        startSection: 3,
        endSection: 4,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFF06B6D4,
        createdAt: now,
        updatedAt: now,
      ),
      Course(
        id: '8',
        name: '马克思主义原理',
        teacher: '周教授',
        location: '文科楼 101',
        dayOfWeek: 4,
        startSection: 5,
        endSection: 6,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFF84CC16,
        createdAt: now,
        updatedAt: now,
      ),
      Course(
        id: '9',
        name: '操作系统',
        teacher: '吴教授',
        location: '信息楼 202',
        dayOfWeek: 5,
        startSection: 1,
        endSection: 2,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFFF97316,
        createdAt: now,
        updatedAt: now,
      ),
      Course(
        id: '10',
        name: '计算机网络',
        teacher: '郑教授',
        location: '信息楼 303',
        dayOfWeek: 5,
        startSection: 3,
        endSection: 4,
        weekRanges: const [
          WeekRange(start: 1, end: 16, type: WeekType.all),
        ],
        colorValue: 0xFF6366F1,
        createdAt: now,
        updatedAt: now,
      ),
    ];
  }
}
